name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Checkout
        uses: actions/checkout@v4

      - 
        name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - 
        name: Build WAR
        run: mvn package

      - 
        name: Copy WAR to Docker Context
        run: cp target/myapp.war $GITHUB_WORKSPACE/target/myapp.war
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: vedadz/warehouse:latest
